API/urls.py
from django.urls import path, include
from . import views
from rest_framework import renderers
from rest_framework.routers import DefaultRouter


lesson_list = views.LessonModelViewSet.as_view({
    'get': 'list',
    'post': 'create'
})

quizziz_detail = views.QuizzizModelViewSet.as_view({
    'get': 'retrieve',
    'put': 'update',
    'patch': 'partial_update',
})
router = DefaultRouter()
router.register(r'words', views.QuizzizModelViewSet)
router.register(r'lessons', views.LessonModelViewSet)

urlpatterns = ([
    path('', include(router.urls)),
    path('lesson/', views.lessons_list , name="wl"),
    path('lesson/<int:pk>/',views.words_detail, name="wd"),

])

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create/lesson/', views.TaoBaiHocTheoMau, name=''),
    path('vi/', views.NgheDienNghia, name='nghediennghia'),
    path('en/', views.NgheDienTu, name='nghedientu'),
    path('quiz/', views.XuLy, name='xuly'),
    path('them-bai-hoc/', views.LessonFormView.as_view(), name='thembaihoc'),
    path('them-tu/', views.QuizzizFormView.as_view(), name='themtu'),
    path('update-words/', views.UpdateWords, name='updatetu'),
    path('update-words/<int:pk>/', views.QuizUpdate.as_view(), name='xulyupdatetu'),
    path('xem-tu/', views.XemTu, name='xemtutheobai'),
    path('tim-tu/', views.FindAllWord, name='findallword'),
    path('random/', views.RandomWord, name='randomword'),
    path('random/quiz/', views.XuLyRandomWord, name='xulyrandomword'),

]

quizziz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('api/', include('API.urls'))
    # path('', include('optimal.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)

core/models.py
from django.db import models

# Create your models here.


class Lesson(models.Model):
    objects = models.Manager()
    lesson_name = models.CharField(default='', max_length=255)

    def __str__(self):
        return self.lesson_name


class Quizziz(models.Model):
    objects = models.Manager()
    word = models.CharField(default='',max_length=255)
    ipa = models.CharField(default='',null=True, blank= True,max_length=255)
    answer = models.CharField(default='', max_length=500)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name="lessons")
    status = models.BooleanField(default=False)
    note = models.CharField(default='', max_length=500 ,null=True, blank= True)
    highlight = models.BooleanField(default=False)

    def __str__(self):
        return self.word

core/forms.py
from django import forms
from .models import Quizziz,Lesson

class QuizzizForm(forms.ModelForm):

    def __init__(self,*args, **kwargs):
        self.status = kwargs.pop('status',None)
        super().__init__(*args,**kwargs)

    def save(self,commit = True):
        quiz = super().save(commit = False)
        quiz.status = self.status
        quiz.answer = quiz.answer+','
        quiz.save()

    class Meta:
        model = Quizziz
        fields = ['word','answer','lesson']
    


class LessonForm(forms.ModelForm):
    def __init__(self,*args, **kwargs):
        super().__init__(*args,**kwargs)

    def save(self):
        lesson = super().save()
        lesson.save()

    class Meta:
        model = Lesson
        fields = ['lesson_name']

core/views.py
from django.shortcuts import render
from core.models import Quizziz,Lesson
from random import randint, random
from django.http import JsonResponse
from django.core import serializers
import json
from django.http import HttpResponse
from django.views import View
from .forms import QuizzizForm,LessonForm
from django.shortcuts import redirect
from gtts import gTTS
# Create your views here.
import os
from quizziz.settings import BASE_DIR
import eng_to_ipa as ipa
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages 

# đọc điền nghĩa
def index(request):
    lessons = Lesson.objects.all()
    rd_words = Quizziz.objects.all().order_by('?')[:12]

    paginator = Paginator(lessons, 20)
    page = request.GET.get('page', 1)
    try:
        lessons_paged = paginator.page(page)
    except PageNotAnInteger:
        lessons_paged = paginator.page(1)
    except EmptyPage:
        lessons_paged = paginator.page(paginator.num_pages)
    context = {
        'rd_words':rd_words,
        'lessons':lessons_paged,
    }
    return render(request, 'core/home.html', context)

#nghe điền nghĩa
def NgheDienNghia(request):
    lessons = Lesson.objects.all()
    rd_words = Quizziz.objects.all().order_by('?')[:13]
    paginator = Paginator(lessons, 20)
    page = request.GET.get('page', 1)
    try:
        lessons_paged = paginator.page(page)
    except PageNotAnInteger:
        lessons_paged = paginator.page(1)
    except EmptyPage:
        lessons_paged = paginator.page(paginator.num_pages)
    context = {
        'rd_words':rd_words,
        'lessons':lessons_paged,
    }
    return render(request, 'core/NgheDienNghia.html', context)

#nghe điền từ
def NgheDienTu(request):
    lessons = Lesson.objects.all()
    rd_words = Quizziz.objects.all().order_by('?')[:13]
    paginator = Paginator(lessons, 20)
    page = request.GET.get('page', 1)
    try:
        lessons_paged = paginator.page(page)
    except PageNotAnInteger:
        lessons_paged = paginator.page(1)
    except EmptyPage:
        lessons_paged = paginator.page(paginator.num_pages)
    context = {
        'lessons':lessons_paged,
        'rd_words':rd_words,
    }
    return render(request, 'core/NgheDienTu.html', context)


def XuLy(request):
    if request.method == "POST":
        form = request.POST
        lesson_id = form.get("lesson_id",None)
        kind =  form.get("kind",None)
        if lesson_id != None:
            lesson = Lesson.objects.get(lesson_name = lesson_id)
            words = Quizziz.objects.filter(lesson = lesson)
            print("================",words)
            if kind == "docdientu":
                title = "Đọc điền nghĩa"
                template = 'core/XuLyDocDienTu.html'
            elif kind == "nghedientu":
                title = "Nghe điền từ"
                template = 'core/XuLyNgheDienTu.html'
            elif kind == "nghediennghia":
                title = "Nghe điền nghĩa"
                template = 'core/XuLyNgheDienNghia.html'
            elif kind == "timtutheobai":
                title = "Xem từ"
                template = 'core/GetWordByLesson.html'
            else:
                return HttpResponse("lỗi sever! 1")
            rd_words = Quizziz.objects.all().order_by('?')[:13]
            context = {
                'title':title,
                'lesson':lesson,
                'words':words,
                'rd_words':rd_words,

            }
        return render(request, template, context)
    else:
        return HttpResponse("lỗi sever!")


class LessonFormView(View):
    def get(self,request):
        form = LessonForm()
        rd_words = Quizziz.objects.all().order_by('?')[:12]

        context = {
           "form":form, 
           "rd_words":rd_words, 
        }
        return render(request, 'core/ThemBaiHoc.html', context)

    def post(self,request):
        form = LessonForm()
        if request.method == 'POST':
            form = LessonForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Create successful!" )
                return redirect('/')
        return HttpResponse("Method is not POST")


class QuizzizFormView(View):
    def get(self,request):
        rd_words = Quizziz.objects.all().order_by('?')[:12]
        lessons = Lesson.objects.all()
        return render(request,'core/ThemTu.html',{'lessons':lessons, 'rd_words':rd_words,})

    def post(self,request):
        if request.method == 'POST':
            lesson = Lesson.objects.get(lesson_name = request.POST.get('lesson',None))
            for i in range(0,int(request.POST.get("number",None))):
                word = request.POST.get('word'+str(i),"")
                mean = request.POST.get('mean'+str(i),"")
                note = request.POST.get('note'+str(i),"")
                ipa = SetIPA(word)
                word = ClearInput(word)
                mean = ClearInput(mean)
                note = ClearInput(note)
                if word != "":
                    if request.POST.get('vital'+str(i),"off")=="on":
                        vital = True
                    else:
                        vital = False
                    if CheckExistWord(word):
                        Quizziz(word=word,answer=mean,lesson=lesson,note=note,highlight=vital,status=True,ipa=ipa).save()
                    else:
                        Quizziz(word=word,answer=mean,lesson=lesson,note=note,highlight=vital,status=False,ipa=ipa).save()
            GetMP3()
            messages.success(request, "Create successful!" )
            return redirect('/')
        return HttpResponse("method is not POST")
        
def SetIPA(word):
    phienam ='/'+ ipa.convert(word)+'/'
    return phienam

def GetMP3():
    quizs = Quizziz.objects.filter(status=False)
    for quiz in quizs:
        numQuizIsLike = Quizziz.objects.filter(word = quiz.word, status = False).count()
        if numQuizIsLike == 1:
            try:
                say = gTTS(quiz.word, lang='en', slow=False)
                name = quiz.word + ".mp3"
                say.save(name)
                os.rename(name,'static/mp3/'+name)
                quiz.status = True
                quiz.save()
                print("create " + name +' sucesses')
            except:
                print("lỗi tạo file " + quiz.word)
        else:
            quiz.status = True
            quiz.save()
    return True


def CheckExistWord(word):
    if Quizziz.objects.filter(word = word).count() >= 1:
        return True
    return False


def ClearInput(input):
    input = input.strip()
    input = input.lower()
    input = input.strip(' \t\n\r')
    return input


def XemTu(request):
    lessons = Lesson.objects.all()
    rd_words = Quizziz.objects.all().order_by('?')[:13]
    paginator = Paginator(lessons, 20)
    page = request.GET.get('page', 1)
    try:
        lessons_paged = paginator.page(page)
    except PageNotAnInteger:
        lessons_paged = paginator.page(1)
    except EmptyPage:
        lessons_paged = paginator.page(paginator.num_pages)
    context = {
        'lessons':lessons_paged,
        'rd_words':rd_words,

    }
    return render(request, 'core/XemTu.html',context)


def FindAllWord(request):
    lessons = Lesson.objects.all()
    words = Quizziz.objects.all()
    rd_words = Quizziz.objects.all().order_by('?')[:13]
    context = {
        'words':words,
        'lessons':lessons,
        'rd_words':rd_words,
    }
    return render(request, 'core/TimTu.html',context)


def RandomWord(request):
    rd_words = Quizziz.objects.all().order_by('?')[:13]
    context = {
        'rd_words':rd_words,
    }
    return render(request, 'core/Random.html', context)



def XuLyRandomWord(request):
    ws = Quizziz.objects.all()
    words = []
    number = int(request.POST.get('so',0))
    for i in range(0,number):
        r  = random.randrange(0, ws.count())
        try:
            print(ws[r])
            words.append(ws[r])

        except:
            pass
    rd_words = Quizziz.objects.all().order_by('?')[:13]

    context = {
        'rd_words':rd_words,
        'words':words,
    }
    return render(request, 'core/XuLyRandom.html', context)


def TaoBaiHocTheoMau(request):

    for i in range(1,20):
        Lesson.objects.create(lesson_name = 'Page ' + str(i) + ' Sheets 1')
    for i in range(1,29):
        Lesson.objects.create(lesson_name = 'Page ' + str(i) + ' Sheets 2')

    return redirect('/')

class QuizUpdate(View):
    def get(self,request,pk):
        rd_words = Quizziz.objects.all().order_by('?')[:12]
        lesson = Lesson.objects.get(pk = pk)
        words = Quizziz.objects.filter( lesson = lesson)
        context = {
            'lessons':lesson, 
            'rd_words':rd_words,
            'words':words,
        }
        return render(request,'core/HandleUpdateWords.html',context)

    def post(self,request,pk):
        lesson = Lesson.objects.get(pk = pk)
        if request.method == 'POST':
            for i in range(0,int(request.POST.get("number",None))):
                print(request.POST.get("number",None))
                id = request.POST.get('id'+str(i),-1)
                word = request.POST.get('word'+str(i),"")
                mean = request.POST.get('mean'+str(i),"")
                note = request.POST.get('note'+str(i),"")
                ipa = SetIPA(word)
                word = ClearInput(word)
                mean = ClearInput(mean)
                note = ClearInput(note)
                if id != -1:
                    try:
                        quiz = Quizziz.objects.get(pk = id)
                        if word != "" :
                            if request.POST.get('vital'+str(i),"off")=="on":
                                vital = True
                            else:
                                vital = False
                            quiz.word = word
                            quiz.ipa = ipa

core/templates/core/GetWordByLesson.html
{% extends 'core/base.html' %}

{% block head%}
  <title>Xem Từ</title>
{% endblock head %}
{% block title %}Xem Từ Theo Bài{% endblock title %}

{% block content %}
    <div class="input-group mt-3 mb-3">
        <div class="input-group-prepend">
            <div class="form-group">
                <div class="input-group-prepend ">
                    <span class="input-group-text">Important</span>
                    <div class="input-group-text">
                        <input type="checkbox" id="ip-important" name="vital0"> 
                    </div>
                </div>
            </div>
        </div>
        <input id="ip-word" type="text" class="form-control" placeholder="Word">
        <input id="ip-mean" type="text" class="form-control" placeholder="Mean">
      </div>
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Word</th>
            <th>IPA</th>
            <th>Mean</th>
            <th>Note</th>
        </tr>
        </thead>
        <tbody id="tbody-data">
            {% for word in words %}
                <tr>
                    <td id="w_{{word.id}}">{{word}}</td>
                    <td style="color:red;">{{word.ipa}}</td>
                    <td>{{word.answer}}</td>
                    <td>{{word.note}}</td>
                </tr>
                <script>
                    $(`#w_{{word.id}}`).on('click',e=>{
                    var audio = new Audio(`/static/mp3/{{word}}.mp3`);
                    audio.play();
                    })
                </script>
            {% endfor %}
        </tbody>
    </table>
    <script>
        const data = []
        var current_data = []
        const ipimportant = document.querySelector('#ip-important')
        const ipmean = document.querySelector('#ip-mean')
        const ipword = document.querySelector('#ip-word')
        const tbody = document.querySelector('#tbody-data')

        {% for word in words %}
            data.push({
                'id':`{{word.id}}`,
                'word':`{{word}}`,
                'ipa': `{{word.ipa}}`,
                'mean':`{{word.answer}}`,
                'note':`{{word.note}}`,
                'lesson':`{{word.lesson}}`,
                'highlight':`{{word.highlight}}`
            })
        {% endfor %}
        
        function LoadDataTable(){
            let txt = ''
            current_data.forEach(ele =>{
                txt += `<tr>
                    <td id="w_${ele.id}">${ele.word}</td>
                    <td style="color:red;">${ele.ipa}</td>
                    <td>${ele.mean}</td>
                    <td>${ele.note}</td>
                </tr>`
            })
            tbody.innerHTML = txt
            current_data.forEach(ele =>{
                $(`#w_${ele.id}`).on('click',e=>{
                    console.log("ok");
                    var audio = new Audio(`/static/mp3/${ele.word}.mp3`);
                    audio.play();
                })
            })
        }

        function ClearInput(input){
            input = input.toLowerCase().trim()
            return input
        }

        ipimportant.addEventListener('change', e =>{
            console.log('a', e.target.checked);
            current_data = []
            if(e.target.checked == false){
                current_data = data
            }else{
                data.forEach(ele => {
                    if(ele.highlight == 'True' ){
                        current_data.push(ele)
                    }
                });
            }
            LoadDataTable()
        })

        ipword.addEventListener("input", e=>{
            current_data = []
            let key = ClearInput(e.target.value)
            data.forEach(ele => {
                if(ele.word.search(key) != -1){
                    current_data.push(ele)
                }
            });
            LoadDataTable()
        })

        ipmean.addEventListener("input", e=>{
            current_data = []
            let key = ClearInput(e.target.value)
            data.forEach(ele => {
                if(ele.mean.search(key) != -1){
                    current_data.push(ele)
                }
            });
            LoadDataTable()
        })

    </script>
{% endblock content %}

{% block table %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Word</th>
          <th>Mean</th>
          <th>Note</th>
        </tr>
      </thead>
      <tbody>
      {% for word in rd_words %}
        <tr>
          <td data-toggle="tooltip" title="Click to listen!" id="{{word.id}}" >{{word}}</td>
          <td>{{word.answer}}</td>
          <td>{{word.note}}</td>
        </tr>
        <script>
        $(`#{{word.id}}`).on('click',e=>{
          var audio = new Audio(`/static/mp3/{{word}}.mp3`);
          audio.play();
        })
        </script>
      {% endfor %}
      </tbody>
    </table>
{% endblock table %}

core/templates/core/HandleUpdateWords.html
{% extends 'core/base.html' %}

{% block head %}
  <title>Cập nhật</title>
{% endblock head %}

{% block title %}Update Words{% endblock title %}
{% block content %}
    <div id="forms">
        <form id="form1" action="" method="post">
            {%csrf_token%}
            {% comment %} <div class="input-group mb-3 package">
                <div class="input-group-prepend ">
                    <span class="input-group-text">Important</span>
                    <div class="input-group-text">
                        <input type="checkbox" name="vital0"> 
                    </div>
                </div>
                <input type="text" class="form-control" placeholder="Word" name="word0" required>
                <input type="text" class="form-control" placeholder="Mean" name="mean0" required>
                <input type="text" class="form-control" placeholder="Note" name="note0">
            </div>   {% endcomment %}

            <input id="phancach" name='number' hidden value="1">
            <div class="d-flex p-3 row">
                <select class="custom-select mt-0 col-sm-8" name="lesson" id="">
                    <option value="{{lessons.lesson_name}}">{{lessons.lesson_name}}</option>
                </select>
                <button class="col-sm-2 them_form btn btn-info" type="button" onclick="themForm()" >Thêm 5 từ</button>
                <button class="col-sm-2 them_form btn btn-warning" type="button" onclick="botForm()" >Bớt 1 từ</button>
            </div>
                        
            <div class="d-flex justify-content-center mb-1">
                <button class="submit_form btn btn-primary btn-lg"  type="submit">Submit</button>
                <button class="submit_form btn btn-outline-secondary  btn-lg"  type="submit"><a href="{% url 'index'%}">Go Back</a></button>
            </div>
        </form>
        
    </div>
{% endblock content %}

{% block table %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Word</th>
          <th>Mean</th>
          <th>Note</th>
        </tr>
      </thead>
      <tbody>
      {% for word in rd_words %}
        <tr>
          <td data-toggle="tooltip" title="Click to listen!" id="{{word.id}}" >{{word}}</td>
          <td>{{word.answer}}</td>
          <td>{{word.note}}</td>
        </tr>
        <script>
        $(`#{{word.id}}`).on('click',e=>{
          var audio = new Audio(`/static/mp3/{{word}}.mp3`);
          audio.play();
        })
        </script>
      {% endfor %}
      </tbody>
    </table>
{% endblock table %}

{% block script %}
    <script>
        var number = 0;
        function themForm(){
            for(i=0;i<5;i++){
                var textForm = `<div class="input-group mb-3 package">
                                    <div class="input-group-prepend ">
                                    <span class="input-group-text">Important</span>
                                    <div class="input-group-text">
                                        <input type="checkbox" name="vital${number}"> 
                                    </div>
                                    </div>
                                    <input required type="text" class="form-control" placeholder="Word" name="word${number}">
                                    <input required type="text" class="form-control" placeholder="Mean" name="mean${number}">
                                    <input type="text" class="form-control" placeholder="Note" name="note${number}">
                                </div>`
                number+=1;
                var newform = document.getElementById("phancach");
                    newform.insertAdjacentHTML("beforebegin",textForm);
            }
            newform.value = number;
        }
        function botForm(){
            var word = document.getElementsByClassName("package");
            word[word.length-1].remove()
            number-=1;
            var newform = document.getElementById("phancach");
            newform.value = number;
        }
        LoadWordToTable()

        function LoadWordToTable(){
            {% for word in words %}
                var textForm = `<div class="input-group mb-3 package">
                                        <div class="input-group-prepend ">
                                        <span class="input-group-text">Important</span>
                                        <div class="input-group-text"> 
                                        <input type="checkbox" name="vital${number}"`
                                        +
                                        {% if word.highlight == True %}
                                            'checked'
                                        {% else %}
                                         ""
                                        {% endif %}
                                        +
                                        `> 
                                        </div>
                                        </div>
                                        <input value="{{word.id}}" type="hidden" name="id${number}">
                                        <input value="{{word.word}}" type="text" class="form-control"  name="word${number}">
                                        <input value="{{word.answer}}" type="text" class="form-control"  name="mean${number}">
                                        <input value="{{word.note}}" type="text" class="form-control" name="note${number}">
                                    </div>`
                number += 1;
                var newform = document.getElementById("phancach");
                    newform.insertAdjacentHTML("beforebegin",textForm);
            {% endfor %}
            newform.value = number;

        }
       
    </script>

{% endblock script %}

core/templates/core/NgheDienNghia.html
{% extends 'core/base.html' %}

{% block head%}
  <title>Nghe điền nghĩa</title>
{% endblock head %}
{% block title %}Nghe điền nghĩa{% endblock title %}

{% block content %}
  <div class="container">
    <form action="{% url 'xuly' %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="kind" value="nghediennghia">
      <div class="row">
        {% for lesson in lessons %}
          <div class="col-sm-3">
            <input style="width:150px" class="quizis btn btn-info" name="lesson_id" type="submit" value="{{lesson.lesson_name}}" >
          </div>
        {% endfor %}
      </div>
    </form>
  </div>
<br>
<nav aria-label="Page navigation example">
    <ul class="pagination pull-right">

        {% if lessons.has_previous %}
        <li><a href="?page={{ lessons.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="disabled"><span>&laquo;</span></li>
        {% endif %}

        {% if lessons.number > 3 %}
        <li><a href="?page=1"><i>1</i></a></li>
        {% endif %}

        {% for i in lessons.paginator.page_range %}
        {% if i > lessons.number|add:"-3" %}
            {% if i < lessons.number|add:"3" %}
                {% if lessons.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endif %}
        {% endif %}
        {% endfor %}

        {% if lessons.number < lessons.paginator.num_pages|add:"-3" %}
        <li><a href="?page={{ lessons.paginator.num_pages }}"><i>{{ lessons.paginator.num_pages }}</i></a></li>
        {% endif %}

        {% if lessons.has_next %}
        <li><a href="?page={{ lessons.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
</nav>
{% endblock content %}

{% block table %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Word</th>
          <th>Mean</th>
          <th>Note</th>
        </tr>
      </thead>
      <tbody>
      {% for word in rd_words %}
        <tr>
          <td data-toggle="tooltip" title="Click to listen!" id="{{word.id}}" >{{word}}</td>
          <td>{{word.answer}}</td>
          <td>{{word.note}}</td>
        </tr>
        <script>
        $(`#{{word.id}}`).on('click',e=>{
          var audio = new Audio(`/static/mp3/{{word}}.mp3`);
          audio.play();
        })
        </script>
      {% endfor %}
      </tbody>
    </table>
{% endblock table %}

core/templates/core/NgheDienTu.html
{% extends 'core/base.html' %}

{% block head%}
  <title>Nghe điền từ</title>
{% endblock head %}
{% block title %}Nghe điền từ{% endblock title %}

{% block content %}
  <div class="container">
    <form action="{% url 'xuly' %}" method="POST">
      {% csrf_token %}
      <input type="hidden" name="kind" value="nghedientu">
      <div class="row">
        {% for lesson in lessons %}
          <div class="col-sm-3">
            <input style="width:150px" class="quizis btn btn-info" name="lesson_id" type="submit" value="{{lesson.lesson_name}}" >
          </div>
        {% endfor %}
      </div>
    </form>
  </div>
<br>
<nav aria-label="Page navigation example">
    <ul class="pagination pull-right">

        {% if lessons.has_previous %}
        <li><a href="?page={{ lessons.previous_page_number }}">&laquo;</a></li>
        {% else %}
        <li class="disabled"><span>&laquo;</span></li>
        {% endif %}

        {% if lessons.number > 3 %}
        <li><a href="?page=1"><i>1</i></a></li>
        {% endif %}

        {% for i in lessons.paginator.page_range %}
        {% if i > lessons.number|add:"-3" %}
            {% if i < lessons.number|add:"3" %}
                {% if lessons.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
            {% endif %}
        {% endif %}
        {% endfor %}

        {% if lessons.number < lessons.paginator.num_pages|add:"-3" %}
        <li><a href="?page={{ lessons.paginator.num_pages }}"><i>{{ lessons.paginator.num_pages }}</i></a></li>
        {% endif %}

        {% if lessons.has_next %}
        <li><a href="?page={{ lessons.next_page_number }}">&raquo;</a></li>
        {% else %}
        <li class="disabled"><span>&raquo;</span></li>
        {% endif %}
    </ul>
</nav>
{% endblock content %}

{% block table %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Word</th>
          <th>Mean</th>
          <th>Note</th>
        </tr>
      </thead>
      <tbody>
      {% for word in rd_words %}
        <tr>
          <td data-toggle="tooltip" title="Click to listen!" id="{{word.id}}" >{{word}}</td>
          <td>{{word.answer}}</td>
          <td>{{word.note}}</td>
        </tr>
        <script>
        $(`#{{word.id}}`).on('click',e=>{
          var audio = new Audio(`/static/mp3/{{word}}.mp3`);
          audio.play();
        })
        </script>
      {% endfor %}
      </tbody>
    </table>
{% endblock table %}

core/templates/core/ThemBaiHoc.html
{% extends 'core/base.html' %}

{% block head%}
  <title>Đọc điền nghĩa</title>
{% endblock head %}

{% block title %}Thêm Bài Học{% endblock title %}

{% block content %}
        <form method="POST">
            {% csrf_token %}
            
            <p class="text-center">Everything you can imagine is real. ― Pablo Picasso</p>
            <div class="field-set row">
                <div class="col-sm-4"></div>
                    <i class="fa fa-book" style="margin: 6px 5px 0 0 ;"></i>
                    <input class="form-control col-sm-4" id="id_lesson_name" name="lesson_name" maxlength="255" type="text" placeholder="Lesson Name" required>
                <div class="col-sm-4"></div>
                <br>

            </div>

            <div class="d-flex justify-content-center mb-1">
                <button class="submit_form btn btn-primary btn-lg"  type="submit">Submit</button>
                <button class="submit_form btn btn-outline-secondary  btn-lg"  type="submit"><a href="{% url 'index'%}">Go Back</a></button>
            </div>

        </form>


{% endblock content %}

{% block table %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Word</th>
          <th>Mean</th>
          <th>Note</th>
        </tr>
      </thead>
      <tbody>
      {% for word in rd_words %}
        <tr>
          <td data-toggle="tooltip" title="Click to listen!" id="{{word.id}}" >{{word}}</td>
          <td>{{word.answer}}</td>
          <td>{{word.note}}</td>
        </tr>
        <script>
        $(`#{{word.id}}`).on('click',e=>{
          var audio = new Audio(`/static/mp3/{{word}}.mp3`);
          audio.play();
        })
        </script>
      {% endfor %}
      </tbody>
    </table>
{% endblock table %}